services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#    volumes:
#      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: wishlist-api
#    volumes:
#      - .:/code
#    depends_on:
#      - db
#    environment:
#      - DBNAME=postgres
#      - DBUSER=postgres=postgres
#      - DBPASSWORD=postgres
#      - DBHOST=db
#      - DBPORT=5432
